[2025-09-17T05:06:44.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-17T04:20:06+00:00 [queued]>
[2025-09-17T05:06:45.808+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-17T04:20:06+00:00 [queued]>
[2025-09-17T05:06:45.856+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-17T05:06:46.344+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_bronze_to_silver> on 2025-09-17 04:20:06+00:00
[2025-09-17T05:06:46.433+0000] {standard_task_runner.py:57} INFO - Started process 1715 to run task
[2025-09-17T05:06:46.494+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_to_silver', 'process_bronze_to_silver', 'manual__2025-09-17T04:20:06+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bronze_to_silver.py', '--cfg-path', '/tmp/tmpskwa2y44']
[2025-09-17T05:06:46.533+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask process_bronze_to_silver
[2025-09-17T05:06:46.822+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-17T05:06:47.958+0000] {task_command.py:416} INFO - Running <TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-17T04:20:06+00:00 [running]> on host f820e4ced8b5
[2025-09-17T05:06:49.419+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_to_silver' AIRFLOW_CTX_TASK_ID='process_bronze_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T04:20:06+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-17T04:20:06+00:00'
[2025-09-17T05:06:49.438+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_bronze_to_silver.py", line 19, in bronze_to_silver
    raise FileNotFoundError(f"Não achei {RAW_FILE}. Coloque o raw_data.csv em data/bronze/.")
FileNotFoundError: Não achei /opt/***/data/bronze/raw_data.csv. Coloque o raw_data.csv em data/bronze/.
[2025-09-17T05:06:49.538+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bronze_to_silver, task_id=process_bronze_to_silver, execution_date=20250917T042006, start_date=20250917T050644, end_date=20250917T050649
[2025-09-17T05:06:49.633+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task process_bronze_to_silver (Não achei /opt/***/data/bronze/raw_data.csv. Coloque o raw_data.csv em data/bronze/.; 1715)
[2025-09-17T05:06:49.749+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-17T05:06:49.929+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
