[2025-09-20T05:24:04.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [queued]>
[2025-09-20T05:24:04.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [queued]>
[2025-09-20T05:24:04.939+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-20T05:24:05.071+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_silver_to_gold> on 2025-09-20 03:29:08+00:00
[2025-09-20T05:24:05.186+0000] {standard_task_runner.py:57} INFO - Started process 630 to run task
[2025-09-20T05:24:05.217+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'silver_to_gold', 'process_silver_to_gold', 'manual__2025-09-20T03:29:08+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_silver_to_gold.py', '--cfg-path', '/tmp/tmpignan1hx']
[2025-09-20T05:24:05.284+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask process_silver_to_gold
[2025-09-20T05:24:05.624+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20T05:24:06.368+0000] {task_command.py:416} INFO - Running <TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [running]> on host 2b8018637437
[2025-09-20T05:24:07.817+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_to_gold' AIRFLOW_CTX_TASK_ID='process_silver_to_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T03:29:08+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T03:29:08+00:00'
[2025-09-20T05:24:08.649+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'idade'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_silver_to_gold.py", line 29, in silver_to_gold
    df["age_band"] = pd.cut(df["idade"], bins=bins, right=True, include_lowest=True, labels=labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'idade'
[2025-09-20T05:24:09.181+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=silver_to_gold, task_id=process_silver_to_gold, execution_date=20250920T032908, start_date=20250920T052404, end_date=20250920T052409
[2025-09-20T05:24:09.253+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task process_silver_to_gold ('idade'; 630)
[2025-09-20T05:24:09.295+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-20T05:24:09.528+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
